name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: yarn install

            - name: Build extension
              run: yarn build

            - name: Package extension
              run: yarn package

            - name: Get tag name from package.json
              id: get_tag_name
              run: echo "TAG_NAME=$(jq -r .version package.json)" >> $GITHUB_ENV

            - name: Create new GitHub release
              id: create_release
              uses: comnoco/create-release-action@v2.0.5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ env.TAG_NAME }}
                  release_name: Release v${{ env.TAG_NAME }}
                  draft: false
                  prerelease: false

            - name: Upload VSIX to GitHub Release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./run-with-tsx-${{ env.TAG_NAME }}.vsix
                  asset_name: run-with-tsx.vsix
                  asset_content_type: application/octet-stream

            - name: Publish to Visual Studio Marketplace
              run: vsce publish
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
