name: Build and Release

on:
    workflow_dispatch:
        inputs:
            version_type:
                description: "Version type (major, minor, patch)"
                required: true
                default: "patch"
                type: choice
                options:
                    - major
                    - minor
                    - patch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: yarn install

            - name: Bump version
              run: yarn version --${{ github.event.inputs.version_type }}

            - name: Get tag name from package.json
              id: get_tag_name
              run: echo "TAG_NAME=$(jq -r .version package.json)" >> $GITHUB_ENV

            - name: Commit version bump
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git commit -am "Bump version to v${{ env.TAG_NAME }}"
                  git push

            - name: Build extension
              run: yarn build

            - name: Package extension
              run: yarn package

            - name: Create new GitHub release
              id: create_release
              uses: comnoco/create-release-action@v2.0.5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ env.TAG_NAME }}
                  release_name: Release v${{ env.TAG_NAME }}
                  draft: false
                  prerelease: false

            - name: Upload VSIX to GitHub Release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./run-with-tsx-${{ env.TAG_NAME }}.vsix
                  asset_name: run-with-tsx.vsix
                  asset_content_type: application/octet-stream

            - name: Publish to Visual Studio Marketplace
              run: npx vsce publish
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
